name: Secrets
on: push
jobs:
  print:
    runs-on: Ubuntu-latest
    env:
      PASSWORD_TEST: ${{ secrets.PASSWORD_TEST }}
    steps:
      - run: echo "${PASSWORD_TEST}"
      - run: echo "${PASSWORD_TEST:0:1} ${PASSWORD_TEST#?}"
